### ISSUE TITLE
Support for Pydantic2

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [exalearn/colmena#118]
I saw that Pydantic is pinned to < 2. It'd be good to eventually add support for Pydantic 2. I don't think this should be particularly hard, seeing as the only instance of calling pydantic is in [the `models` module](https://github.com/exalearn/colmena/blob/e874901aee2b16a7a537ffc2ef99847c7508f844/colmena/models.py).

Note: I'm not asking you to do this :) just making a note. I might tackle it when a get a spare moment! Most of my software stack is now set to pydantic >= 2.

**Comment by WardLT** [comment]
Thanks for pointing this out! I haven't learned Pydantic v2 yet and haven't encountered an environment problem due to pinning, but know it is coming 😬
