### ISSUE TITLE
Value server: Removing large objects from task descriptions

### ISSUE THREAD

**Issue by WardLT** [exalearn/colmena#17]
Colmena applications may use large objects that are re-used between tasks (e.g., machine learning models). We could remove the need to send these objects with every task submission and open the door to other ways of reducing communication costs (e.g., collective communication between workers).

One model I have been thinking about is a method that lets client applications push objects to a store (Value Server) and then passing pointers to the data that are resolved by the method server. A basic flow would look like: 

![value-server](https://user-images.githubusercontent.com/7003149/97727404-5a798380-1a9e-11eb-8423-d8d3590865f7.png)

We would have a fair amount of work to do for an initial prototype:

- [ ] Implement a value server that can be accessed by client and workers
- [ ] Create a "data pointer" object 
- [ ] Allow method server or client to pass value server configuration to workers (or, alternatively)
- [ ] Add logic to resolve data pointers to [wrapper function](https://github.com/exalearn/colmena/blob/657f58a8ebe0d0b57b602104fd73d8ad370c4c34/colmena/method_server/parsl.py#L21). It should scan the inputs and outputs for data pointers, and then act to pull/push objects.

I think the largest opportunity for optimization is in the wrapper function. We could introduce...

- caching and checking if a server has an updated version of the object before pulling
- a pub/sub model to cache data objects ahead-of-time with collective communication
- performing additional deserialization routines (e.g., compiling a tensorflow model) asynchronously. For example, see [MPNNMessage](https://github.com/exalearn/colmena/blob/657f58a8ebe0d0b57b602104fd73d8ad370c4c34/molecule-design/moldesign/score/mpnn.py#L12)'s `get_model` function that actually builds the model from the weights and configuration stored in the message. At present, this is [executed lazily](`https://github.com/exalearn/colmena/blob/657f58a8ebe0d0b57b602104fd73d8ad370c4c34/molecule-design/moldesign/score/mpnn.py#L77`) but could be done eagerly when the model data is received by a worker.

**Comment by gpauloski** [comment]
@WardLT, we can close this now? And if so do we want to open new issues for the last two bullet points?

**Comment by WardLT** [comment]
Let's close it. Those last two ideas are things we can get to later
