### ISSUE TITLE
CPU/GPU Affinity for Parsl Workers

### ISSUE THREAD

**Issue by WardLT** [exalearn/colmena#5]
Tensorflow utilizes all resources on a node unless partitioned otherwise, and I suspect other NN frameworks are similar. Given the prevalence of NNs in target Colmena applications, we should bake in ways of running >1 ML tasks per node without having them compete for resources.

Note: Adding in resource pinning for workers might be better suited for Parsl (@yadudoc ?)

**Comment by yadudoc** [comment]
My understanding is that tensorflow provides a mechanism to detect and bind to CPUs/GPUs. There are some examples in their [docs](https://www.tensorflow.org/guide/gpu). Any examples that show such requirements would be great. This quickly gets into box-packing on CPU,GPU,Walltime (maybe unlimited) and Memory.
