### ISSUE TITLE
API bug in synthetic-data example

### ISSUE THREAD

**Issue by braceal** [exalearn/colmena#63]
In the synthetic-data example a `value_server_threshold` parameter is passed to `make_queue_pairs`, however, this parameter is not part of the function signature. Should it be updated to `proxystore_threshold`? In addition, is it necessary to specify the `proxystore_name` parameter for `proxystore_threshold` to have an effect? Thanks!

Code:
https://github.com/exalearn/colmena/blob/master/demo_apps/synthetic-data/synthetic.py#L159
```
client_queues, server_queues = make_queue_pairs(
        args.redis_host,
        args.redis_port,
        topics=["generate"],
        serialization_method="pickle",
        keep_inputs=False,
        value_server_threshold=value_server_threshold,
    )
```

**Comment by gpauloski** [comment]
Hi @braceal! Sorry for the late reply. I reworked the synthetic app in the [syn-app-updates](/exalearn/colmena/tree/syn-app-updates) branch since, as you pointed out, was no longer up-to-date with Colmena'a features! 

It should still work fine, but I'll verify and open a PR for it soon.
